#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKSPACE_DIR="${SCRIPT_DIR%/scripts}"

export UV_CACHE_DIR="${UV_CACHE_DIR:-$WORKSPACE_DIR/.cache/uv}"
export HF_HOME="${HF_HOME:-$WORKSPACE_DIR/.cache/huggingface}"
export ALPAMAYO_WORKSPACE="${ALPAMAYO_WORKSPACE:-$WORKSPACE_DIR}"
export ALPAMAYO_MODEL_DIR="${ALPAMAYO_MODEL_DIR:-$WORKSPACE_DIR/artifacts/models/alpamayo_r1_training}"
export ALPAMAYO_PAI_LOCAL_DIR="${ALPAMAYO_PAI_LOCAL_DIR:-$WORKSPACE_DIR/artifacts/pai}"
export ALPAMAYO_LOG_DIR="${ALPAMAYO_LOG_DIR:-$WORKSPACE_DIR/artifacts/cosmos_rl_logs}"
export ALPAMAYO_STAGE1_OUT="${ALPAMAYO_STAGE1_OUT:-$WORKSPACE_DIR/artifacts/sft_stage1}"
export ALPAMAYO_STAGE2_OUT="${ALPAMAYO_STAGE2_OUT:-$WORKSPACE_DIR/artifacts/sft_stage2}"
export ALPAMAYO_RL_EXPORT_DIR="${ALPAMAYO_RL_EXPORT_DIR:-$WORKSPACE_DIR/artifacts/rl_exported_model}"
export ALPAMAYO_RL_OUTPUT_DIR="${ALPAMAYO_RL_OUTPUT_DIR:-$WORKSPACE_DIR/artifacts/cosmos_rl_train_output}"

mkdir -p \
  "$UV_CACHE_DIR" \
  "$HF_HOME" \
  "$ALPAMAYO_MODEL_DIR" \
  "$ALPAMAYO_PAI_LOCAL_DIR" \
  "$ALPAMAYO_LOG_DIR" \
  "$ALPAMAYO_STAGE1_OUT" \
  "$ALPAMAYO_STAGE2_OUT" \
  "$ALPAMAYO_RL_EXPORT_DIR" \
  "$ALPAMAYO_RL_OUTPUT_DIR"

echo "ALPAMAYO_WORKSPACE=$ALPAMAYO_WORKSPACE"
echo "ALPAMAYO_MODEL_DIR=$ALPAMAYO_MODEL_DIR"
echo "ALPAMAYO_PAI_LOCAL_DIR=$ALPAMAYO_PAI_LOCAL_DIR"
echo "ALPAMAYO_LOG_DIR=$ALPAMAYO_LOG_DIR"
echo "ALPAMAYO_STAGE1_OUT=$ALPAMAYO_STAGE1_OUT"
echo "ALPAMAYO_STAGE2_OUT=$ALPAMAYO_STAGE2_OUT"
echo "ALPAMAYO_RL_EXPORT_DIR=$ALPAMAYO_RL_EXPORT_DIR"
echo "ALPAMAYO_RL_OUTPUT_DIR=$ALPAMAYO_RL_OUTPUT_DIR"
